#!/usr/bin/env bash
# type: sbatch -J name -t time --mem MB script.sh "[13:31]"
# Keep lines starting with #SBATCH together and at top of script! Modify settings as appropriate.
# high pass filter
#
#SBATCH -J hpf				# Job name
#SBATCH -o ../../output/FSL_hpf-%j.out		# Output file name
#SBATCH -p all					# Set partition to 'all' (don't change)
#SBATCH --workdir=./				# Set working directory
#SBATCH -t 1440					# Set runtime in hh:mm:ss, d-hh, d-hh:mm, mm:ss, or m
#SBATCH --mem-per-cpu 10240			# Set amount of memory in MB (1GB = 1024 MB)
#SBATCH -c 2					# number of cpus reserved for job
#SBATCH --mail-user=miriamw@princeton.edu	# Set user email for notifications
#SBATCH --mail-type=ALL				# Set notification type

pushd ../ > /dev/null
source globals.par
source funcs
popd > /dev/null

wd=/jukebox/tamir/miriamw/pipeline/msadapt/prep/TSK/aNrFuNwDsD/
wd_new=/jukebox/tamir/miriamw/pipeline/msadapt/prep/TSK/aNrFuNwDsD_filtered/

subs=( "$@" )
get_subs a b ${subs[@]}


for s in ${SUBS[@]}; do
    for r in {1..4}; do
        fslmaths ${wd}${s}/epi_r0${r}.nii.gz -bptf 25 -1 ${wd}${s}/fepi_r0${r}.nii.gz
        echo "filtered epi_r0${r}.nii.gz for sub $s"
    done
    cp ${wd}${s}/anat.nii.gz ${wd_new}${s}/
    cp ${wd}${s}/*.par ${wd_new}${s}/
    echo "done with sub $s"
done

update_nii ${wd} f SUBS[@]
