#!/usr/bin/env bash
# type: sbatch -J name script.sh sub
# sub should be singular subject number or ID

#SBATCH -J run_SPMw_prep		# Job name
#SBATCH --workdir=./			# Set working directory
#SBATCH -o ../../output/SPMw-%j.out
#SBATCH -t 24:00:00				# Set runtime in hh:mm:ss, d-hh, d-hh:mm, mm:ss, or m
#SBATCH --mem 5120				# Set amount of memory in MB (1GB = 1024 MB)

source ../globals.par

pushd ../ > /dev/null
source funcs
popd > /dev/null 

label='[SPM12W]'
logfile=LOG.txt

# first arg is pfile
pfile=$1
# second arg is subjectID
sub=$2; num2subID sub
subid=$SUBIDS

echo "${label} $(date) Beginning DARTEL analysis of subject ${subid} with pfile ${pfile}" >> "${logfile}"
# run matlab from the command line as part of a submit job
module load matlab/R2015b
matlab -nosplash -nodisplay -nodesktop -r "try; SPM12w_preprocess('${subid}', '${pfile}', '${PKG_DIR}/'); catch me; fprintf('%s / %s\n',me.identifier,me.message); end; exit"

echo "${label} Done. $(date)" >> "${logfile}"
