#!/bin/bash -e/
# author: Miriam Weaverdyck 8/9/16
# ------------------------------------------------------------------------------

if ! [[ $# -eq 2 ]]; then echo "write_step_par must have 2 input arguments!  Aborting..."; exit; fi

source pars.par

cat <<EOT > step.par
# turn off everything
QA='none'
SLICE_TIME='none'
REALIGN='none'
UNWARP='none'
SMOOTH_SOFT='none'
SMOOTH=$SMOOTH
SNR='none'
SLICES=0

# turn on current step
$1='$2'
EOT

echo "Finished writing step.par"