#!/bin/bash -e
# author: Miriam Weaverdyck 8/1/16
# ------------------------------------------------------------------------------
# this script writes out the parameters to the p_study.m file 
# (a matlab file to be read by SPM12w)

set -e # stop immediately when an error occurs

pushd `dirname $0` > /dev/null   # move into this directory, quietly

source pars.par
source ../scripts/globals.par

# set file name and folder based on whether or not this is a temp pfile
if [[ $# -eq 0 ]]; then fname=''; wd_raw=$PREP_DIR_RAW; 
	source pars.par
elif [[ $# -eq 1 ]]; then fname="_temp_$1"; wd_raw=$PREP_DIR_WD; 
	source step.par
else echo "You must input 0 or 1 arguments: 0 to create a general pfile, 1 to create a temporary pfile with the inputted extension.";
	echo "Aborting..."; exit; fi
	
popd > /dev/null   # return to the previous directory, quietly

save_dir=$PROJECT_DIR/$SCRIPT_DIR_DARTEL
fname_full=$save_dir/p_DARTEL$fname.m




if [[ $NORM != 'DARTEL' ]]; then
	echo "ABORTING: DARTEL was not chosen for normalization in /notes/pars.par."
	exit 0
fi




spm8_dir=$PKG_DIR/SPM8
NIfTI_dir=$PKG_DIR/NIfTI

if [[ $NORM == 'DARTEL' ]]; then norm=1; else norm=0; fi

if [[ $SMOOTH_SOFT == 'DARTEL' ]]; then	smooth=$SMOOTH; else smooth=0; fi

if [[ $REALIGN == 'DARTEL' ]]; then realign=1; else realign=0; fi

sub_dir=prep/wd

cat <<EOT > $fname_full
% Parameters file for SPM8 DARTEL normalization
% Last updated: August 2016
% =======1=========2=========3=========4=========5=========6=========7=========8

% SPM packages to load
p.spm8_dir      = '$spm8_dir';
p.NIfTI_dir     = '$NIfTI_dir';
p.scripts_dir   = '$SCRIPT_DIR_SPM8';

% study directory
p.proj_dir      = '$PROJECT_DIR';
p.output        = '$OUT_DIR';

% execute the job immediately? (0 = no, 1 = yes)
p.execTAG       = 1;

% customizable preprocessing parameters
p.vox_size      = $VOX_SIZE;
p.smooth        = $smooth;
p.normalize	= $norm;
p.realign	= $realign;

% subjects directory containing subject folders
p.subdir        = '$sub_dir';
% pattern for finding subject folders (use wildcards)
p.subID         = 's*';
% do which subjects? ('all' to do all, position vector, e.g. 1:4, to do a subset)
%p.subTAG        = 'all';
% pattern for finding functional run files (use wildcards)
p.runID         = 'epi_r*';
% pattern for finding matched-bandwidth image (use wildcards)
p.mprageID      = 'anat.nii';

% format of your raw functional images (1=img/hdr, 2=4D nii)
p.funcFormat    = 2;

% path for tissue probability maps (in spm8/tpm) for 'new segment'
p.TPMimg        = '$spm8_dir/toolbox/Seg/TPM.nii';

EOT
echo "Parameters file $fname_full written and saved."
