#!/usr/bin/env bash
# Author: Miriam
# 9/19/16 edited by MEW to extract prefix string from pfile name and update_nii
###########################################
# Arguments (>=2 total):
#  pfile 	: pfile for SPM12w to use
#  subs		: subjects to run (e.g. 1 2 3 will run subs s001, s002, and s003). Should NOT be an array
###########################################

#SBATCH -J dartel_prep								# Job name
#SBATCH --workdir=./							# Working directory
#SBATCH -o ../../output/DARTEL_prep-%j.out 		# Output file
#SBATCH --mem-per-cpu=20480						# Amount of memory in MB (1GB = 1024 MB)
#SBATCH --mail-type=ALL							# Type of emails to send
#SBATCH -t 2880									# Time : Default time is 48 hours (2880 min)
#SBATCH -p all                                	# DON'T CHANGE

pushd ../ > /dev/null
source globals.par
source funcs
popd > /dev/null 

label='[DARTEL]'

if [[ ! $# -ge 2 ]]; then 
	echo "${label} At least 2 input arguments needed: pfile and (at least one) subject(s). Aborting..."; exit; 
fi

# first arg is pfile
pfile=$1
# rest of args are subs (each arg separated by a space)
shift 
SUBIDS=( "$@" )

# extract the wd folder location from the pfile by grabbing the quoted section of the line that starts with "p.subdir /whitespace/ = " and ends before ";"
wd_dir=$(grep -oP 'p.subdir\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')

# extract prefix list from parameters file by finding the string between 3 uppercase letters and .m
steps=$(echo "${pfile}" | grep -Po '.*\_[A-Z][A-Z][A-Z]\K.*?(?=.m)')

# get wd dartel logfile
# if normalization is in steps, logfile should be in wd folder (group processesing). If not, then only one subject so log to sdir
if [[ ${steps} =~ w ]]; then logfile=${wd_dir}/LOG_dartel.txt; 
else 
	logfile=${wd_dir}/${SUBIDS}/LOG_dartel.txt; 
	if [[ ${#SUBIDS[@]} -gt 1 ]]; then echo "${label} WARNING: More than one subject being run without normalization.  Logfile = ${logfile}"; fi
fi

logfile_wd=${wd_dir}/LOG.txt

# turn SUBIDS into a matlab array of numbers (not subIDs)
make_matlab_array SUBIDS[@]

echo "${label} $(date) Beginning DARTEL analysis of subject(s) ${matlab_array} with pfile ${pfile}" | tee -a "${logfile_wd}"

# unzip the epi* and anat files in the subject directories within wd_dir
unzip_epi_anat ${wd_dir} SUBIDS[@]

# load matlab script
module load matlab/R2015b
matlab -nosplash -nodisplay -nodesktop -r "try; DARTEL_spm8_vars(${matlab_array},'$pfile'); catch me; fprintf('%s / %s\n',me.identifier,me.message); end; exit" | tee -a "${logfile}"

unset $prefix
for (( i=0; i<${#steps}; i++ )); do
    step="${steps:$i:1}";
    #skip realignment and unwarping 
    if [[ $step == r ]] || [[ $step == u ]]; then continue; fi;
    prefix=${prefix}${step};
done
steps=$prefix

# update epi_r##.nii* files to their most recent versions
update_nii ${wd_dir} ${steps} SUBIDS[@]

echo "${label} Done. $(date)" | tee -a "${logfile_wd}"
