#!/usr/bin/env bash
# Author: Miriam
# 9/19/16 edited by MEW to extract prefix string from pfile name and update_nii

#SBATCH -J dartel						# Job name
#SBATCH --workdir=./					# Set working directory
#SBATCH -o ../../output/dartel-%j.out 	# Set output file
#SBATCH --mem-per-cpu=20480				# Set amount of memory in MB (1GB = 1024 MB)
#SBATCH --mail-type=END,FAIL			# Set type of emails to send
#SBATCH -t 2880							# Default time is 48 hours (2880 min)

pushd ../ > /dev/null
source globals.par
source funcs
popd > /dev/null 

label='[DARTEL]'
logfile=LOG.txt

# first arg is pfile
pfile=$1
# rest of args are subs (each arg separated by a space)
shift 
SUBS=( "$@" )

# turn SUBS into a matlab array of numbers (not subIDs)
make_matlab_array SUBS[@]

echo "${label} $(date) Beginning DARTEL analysis of subject(s) ${matlab_array} with pfile ${pfile}" >> "${logfile}"

# extract prefix list from parameters file by finding the string between 3 uppercase letters and .m
steps=$(echo "${pfile}" | grep -Po '.*\_[A-Z][A-Z][A-Z]\K.*?(?=.m)')

# extract the wd folder location from the pfile by grabbing the quoted section of the line that starts with "p.subdir /whitespace/ = " and ends before ";"
wd_dir=$(grep -oP 'p.subdir\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')

# unzip the epi* and anat files in the subject directories within wd_dir
unzip_epi_anat ${wd_dir} SUBS[@]

# load matlab script
module load matlab/R2015b
matlab -nosplash -nodisplay -nodesktop -r "try; DARTEL_spm8_vars(${matlab_array},'$pfile'); catch me; fprintf('%s / %s\n',me.identifier,me.message); end; exit"

# update epi_r##.nii* files to their most recent versions
update_nii ${wd_dir} ${steps} SUBS[@]

echo "${label} Done. $(date)" >> "${logfile}"
