#!/bin/bash
#This script runs QA on converted data in raw and puts it in qa. 
#Standard version only runs SFNR and masked center of mass on epi's (excluding spin echos'). See below for other QA options
# August 5, 2016 Judith Mildner
###########################################
# Packages used:
#  BXH
# Arguments:
#  None
#
###########################################
#SBATCH -J "bxh_qa"
#SBATCH -o ../output/bxh_qa_%j.out
#SBATCH -p all
#SBATCH --mail-type=FAIL


set -e

source globals.par

module load bxh
GLOBIGNORE=*_SE_* #exclude spin echo's from search for epi's. BXH tools will throw an error if you try to QA these

echo
for task in ${TASKS[@]}; do
  for rawpath in ${PROJECT_DIR}/raw/${task}/*/; do
    subject=$(basename "$rawpath")
  if [ -e ${PROJECT_DIR}/qa/${subject}/${task} ]; then
    echo "[QA] QA already exists for ${subject} on task ${task}. Skipping ${subject}."
    continue
  fi
  echo [QA]
  for scan in ${rawpath}epi*.nii*; do
    echo "[QA] Creating BXH header for $scan at $(date)" 
    analyze2bxh ${scan} ${scan%.nii*}.bxh #create bxh header for the first scan
  done
  echo "[QA] Starting QA for $subject at $(date)"
  mkdir -p "${PROJECT_DIR}/qa/${subject}/"
  sbatch -t 2880 bxh_generate $rawpath $PROJECT_DIR $subject $task
  # To run all QA options, remove --calc meanstddevsfnr,maskedcmass. Load bxh module and run fmriqa_generate.pl without arguments for more details.
done
done

echo "[QA] Done. $(date)"
echo
