#!/bin/bash
#
# Run QA script for a certain subject and task
# Input arguments:
# rawpath
# PROJECT_DIR
# subject
# task
#SBATCH -J bxh_qa
#SBATCH -o ../output/bxh_qa-%j.out
#SBATCH -p all

rawpath=$1
PROJECT_DIR=$2
subject=$3
task=$4


module load bxh

fmriqa_generate.pl --calc meanstddevsfnr,maskedcmass ${rawpath}*.bxh "${PROJECT_DIR}/qa/${task}/${subject}"

source ${PROJECT_DIR}/scripts/globals.par

new_line=$(python sfnr.py -i "${PROJECT_DIR}/qa/${task}/${subject}/index.html" -p $PKG_DIR)

#Add the new line to the overview file and sort the file by sub number
echo "${subject},${new_line}" >> "${PROJECT_DIR}/qa/${task}/sfnr_all.csv"
sort -k1 -n -t, "${PROJECT_DIR}/qa/${task}/sfnr_all.csv" -o "${PROJECT_DIR}/qa/${task}/sfnr_all.csv"
