#!/bin/bash
# get_subs function
# author: Miriam Weaverdyck August 3, 2016
# This function returns an array of subjects.  
# No argument is given: will output an array of just the new subjects preprocessed.  
# Argument = 'all': will include all subjects listed in raw/
# Argument is an array: outputs those subjects in correct subID format
#
# Uses globals.par: RAW_DIR, PREP_DIR
# Outputs: SUBS (array of subjects in form s000)
# ------------------------------------------------------------------------------


function get_subs {
	unset SUBS
	source globals.par  
	source num2subID

	if [[ $# -eq 0 ]]; then
		# NEW SUBJECTS: no input means run all new subjects only, based on raw/
		# make list of all subjects in raw/
		i=0
		for s in $(ls -d $RAW_DIR/*/ | xargs -n 1 basename); do
			subs_all[$i]=$s
			i=$i+1
		done
		# check list of subjects with those in prep
		i=0
		for s in "${subs_all[@]}"; do
			echo "searching for $s"
			for d in $(ls -d $PREP_DIR/*/); do
				echo "looking in $d"
				for p in $(ls -d $d/*/ | xargs -n 1 basename); do
					echo "examining $p"
					if [[ $s == $p ]]; then
						# found folder with same name as subject.  Delete from list
						echo "Deleting ${subs_all[$i]} from list of all subs..."
						unset subs_all[$i]
						i=$i+1
						continue
					fi
				done
			done
		done
		# Make list of all new subjects, ignoring the empty elements
		i=0
		for s in "${subs_all[@]}"; do
			if [[ ! -z $s ]]; then
				SUBS[$i]=$s
				i=$i+1
			fi
		done
		# SUBS now contains an array of new subjects that have not been preprocessed
		echo 'No subjects given. Selecting new subjects:'
		echo "${SUBS[@]}"
	elif [[ $1 == 'all' ]]; then
		# ALL SUBJECTS: run all subjects, even those who have already been preprocessed
		i=0
		for s in $(ls -d $RAW_DIR/*/ | xargs -n 1 basename); do
			SUBS[$i]=$s
			i=$i+1
		done
		echo 'Selecting all subjects:'
		echo "${SUBS[@]}"
	else
		# RUN SELECT SUBJECTS: run only the subjects inputted, even if already preprocessed
		declare -a subs_array=("${!1}")
		# convert subject numbers to form (s000)
		num2subID subs_array[@]
		SUBS="${SUBIDS[@]}"

		echo 'Selecting these subjects only:'
		echo "${SUBS[@]}"
	fi
}
