#!/bin/bash
# retrieve_from_conquest copies one subject's folder from conquest to the study directory in /jukebox/ and then runs retrieve_dcm, which copies the dicoms
# from /jukebox/ into a zipped archive folder in /studydir/arch/dicom/
################################################################################---------- 
# Packages used:
#  none
# Files sourced:
#  globals.par
# Arguments (exactly 2 required):
#  YYMMDD	: the date you ran the subject - must be the first 6 characters in the subject folder's name
#  ### 		: the 3-digit subject number (no 's')
################################################################################----------

source globals.par

# Make sure there are 2 input args
if [[ $# -ne 2 ]]; then 
	echo "2 arguments needed: run_date (YYMMDD) and subnum (###). Will look for run_date*subnum-* in Conquest and rename to run_date_PROJECT_NAME_subnum. Aborting..."; exit; 
fi

run_date=$1
# figure out the year based on inputted run_date
run_year="20${run_date:0:2}"
subnum=$2

# capitalize first character in LAB_NAME and SCANNER
lab="$(tr '[:lower:]' '[:upper:]' <<< ${LAB_NAME:0:1})${LAB_NAME:1}"
SCANNER="$(tr '[:lower:]' '[:upper:]' <<< ${SCANNER:0:1})${SCANNER:1}"

# store final subject name (YYMMDD_study_subnum)
subdir_name=${run_date}_${PROJECT_NAME}_${subnum}

# store full subject directories in conquest and jukebox
#conquest_subdir=/jukebox/dicom/conquest/${SCANNER}-*/${lab}*/${run_year}/${run_date}*${subnum}-*
conquest_subdir=/jukebox/dicom/conquest/${SCANNER}-*/${lab}*/*/${run_date}*${subnum}-*
jukebox_subdir=${BACKUP_DIR}/raw/${subdir_name}

# copy subject's directory from conquest to jukebox
echo "Copying subject from conquest to jukebox: ${conquest_subdir} -> ${jukebox_subdir}"
cp -r ${conquest_subdir} "${jukebox_subdir}"

echo "Done copying. Running retrieve_dcm ${subdir_name}"

# run retrieve_dcm to bring subject into study folder on /fastscratch/
bash retrieve_dcm ${subdir_name}
